// Code generated by ack-generate. DO NOT EDIT.
// This file is regenerated on each run of `ack-generate e2e-tests`.

package e2e

import (
	"context"
	"log"
	"os"
	"testing"

	"github.com/aws/aws-sdk-go-v2/config"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/{{ .ServicePackageName }}"
	"k8s.io/apimachinery/pkg/runtime"
	clientgoscheme "k8s.io/client-go/kubernetes/scheme"

	svcapitypes "github.com/aws-controllers-k8s/{{ .ControllerName }}-controller/apis/{{ .APIVersion }}"
	acktest "github.com/aws-controllers-k8s/test-infra/pkg/e2e"
{{- if .TestConfig.Bootstrap }}
	"github.com/aws-controllers-k8s/test-infra/pkg/e2e/bootstrap"
{{- end }}
)
{{ if .TestConfig.Bootstrap }}
var bootstrapResources *bootstrapState

type bootstrapState struct {
{{- range .TestConfig.Bootstrap }}
	{{ .Name }} *bootstrap.{{ .Type }}Resource
{{- end }}
}
{{ end }}
var awsClient *svcsdk.Client

func TestMain(m *testing.M) {
	scheme := runtime.NewScheme()
	_ = clientgoscheme.AddToScheme(scheme)
	_ = svcapitypes.AddToScheme(scheme)

	acktest.SetScheme(scheme)
	acktest.Setup()

	ctx := context.Background()
	awsCfg, err := config.LoadDefaultConfig(ctx)
	if err != nil {
		log.Fatalf("failed to load AWS config: %v", err)
	}
	awsClient = svcsdk.NewFromConfig(awsCfg)
{{ if .TestConfig.Bootstrap }}
	clients, err := bootstrap.NewClients(ctx)
	if err != nil {
		log.Fatalf("failed to create bootstrap clients: %v", err)
	}

	bootstrapResources = &bootstrapState{}
{{- range .TestConfig.Bootstrap }}
	bootstrapResources.{{ .Name }} = bootstrap.New{{ .Type }}("{{ .Name }}", clients)
{{- end }}

	resources := []bootstrap.Resource{
{{- range .TestConfig.Bootstrap }}
		bootstrapResources.{{ .Name }},
{{- end }}
	}
	if err := bootstrap.SetupAll(ctx, resources); err != nil {
		log.Fatalf("bootstrap setup failed: %v", err)
	}
{{ end }}
	code := m.Run()
{{ if .TestConfig.Bootstrap }}
	bootstrap.TeardownAll(ctx, resources)
{{ end }}
	acktest.Teardown()
	os.Exit(code)
}
