# Code generated by ack-generate. DO NOT EDIT.
# This file is regenerated on each run of `ack-generate e2e-tests`.

SHELL := /bin/bash # Use bash syntax

# Set up variables
GO111MODULE=on

# Build ldflags
VERSION ?= "v0.0.0"
GITCOMMIT=$(shell git rev-parse HEAD)
BUILDDATE=$(shell date -u +'%Y-%m-%dT%H:%M:%SZ')
GO_LDFLAGS=-ldflags "-X main.version=$(VERSION) \
			-X main.buildHash=$(GITCOMMIT) \
			-X main.buildDate=$(BUILDDATE)"

AWS_REGION ?= us-west-2
E2E_TEST_NAMESPACE ?= default
CONTROLLER_HEALTHZ_ADDR ?= 0.0.0.0:8081
CONTROLLER_LOG_FILE ?= controller.log

.PHONY: all test local-test build-controller install-crds run-e2e

all: test

test: 				## Run code tests
	go test -v ./...

local-test: 		## Run code tests using go.local.mod file
	go test -modfile=go.local.mod -v ./...

build-controller: 	## Build the controller binary
	@echo "building controller binary..."
	@go build ${GO_LDFLAGS} -o bin/controller cmd/controller/main.go

install-crds: 		## Install CRDs into the current cluster
	@echo "installing CRDs..."
	@kubectl apply -f config/crd/bases/
	@kubectl apply -f config/crd/common/bases/ 2>/dev/null || true

run-e2e: build-controller install-crds ## Run generated Go e2e tests with local controller
	@echo "starting controller locally (logs: $(CONTROLLER_LOG_FILE))..."
	@./bin/controller \
		--aws-region $(AWS_REGION) \
		--watch-namespace $(E2E_TEST_NAMESPACE) \
		--enable-development-logging=true \
		--log-level debug \
		--enable-leader-election=false \
		--healthz-addr $(CONTROLLER_HEALTHZ_ADDR) > $(CONTROLLER_LOG_FILE) 2>&1 & \
	CONTROLLER_PID=$$!; \
	echo "controller started (PID: $$CONTROLLER_PID)"; \
	echo "waiting for controller to become ready..."; \
	for i in $$(seq 1 30); do \
		if curl -sf http://$(CONTROLLER_HEALTHZ_ADDR)/readyz > /dev/null 2>&1; then \
			echo "controller is ready"; \
			break; \
		fi; \
		if ! kill -0 $$CONTROLLER_PID 2>/dev/null; then \
			echo "ERROR: controller process exited unexpectedly"; \
			exit 1; \
		fi; \
		sleep 1; \
	done; \
	if ! curl -sf http://$(CONTROLLER_HEALTHZ_ADDR)/readyz > /dev/null 2>&1; then \
		echo "ERROR: controller did not become ready within 30s"; \
		kill $$CONTROLLER_PID 2>/dev/null; \
		exit 1; \
	fi; \
	echo "running e2e tests..."; \
	ACK_TEST_NAMESPACE=$(E2E_TEST_NAMESPACE) AWS_REGION=$(AWS_REGION) \
		go test -v -timeout 30m ./test/e2e-go/...; \
	TEST_EXIT=$$?; \
	echo "stopping controller (PID: $$CONTROLLER_PID)..."; \
	kill $$CONTROLLER_PID 2>/dev/null; \
	wait $$CONTROLLER_PID 2>/dev/null; \
	exit $$TEST_EXIT

help:           	## Show this help.
	@grep -F -h "##" $(MAKEFILE_LIST) | grep -F -v grep | sed -e 's/\\$$//' \
		| awk -F'[:#]' '{print $$1 = sprintf("%-30s", $$1), $$4}'
