// Code generated by ack-generate. DO NOT EDIT.
// This file is regenerated on each run of `ack-generate e2e-tests`.

package e2e

import (
	"context"
	"testing"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/{{ .ServicePackageName }}"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/{{ .ServicePackageName }}/types"
	"github.com/stretchr/testify/require"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/{{ .ControllerName }}-controller/apis/{{ .APIVersion }}"
	acktest "github.com/aws-controllers-k8s/test-infra/pkg/e2e"
)

// Ensure imports are used.
var (
	_ = aws.String
	_ = svcsdk.New
	_ = svcsdktypes.NoSuchBucket{}
)
{{ range $idx, $test := .Tests }}
func Test{{ $.CRD.Kind }}_{{ $test.TestNameCamel }}(t *testing.T) {
	// t.Parallel()
	ctx := context.Background()
	name := acktest.RandomName("{{ $.CRD.Names.Snake | TruncateTo 12 }}", 40)

	t.Logf("test starting for {{ $.CRD.Kind }} with name %s", name)

	resource := &svcapitypes.{{ $.CRD.Kind }}{
		ObjectMeta: metav1.ObjectMeta{
			Name:      name,
			Namespace: acktest.Namespace(),
		},
		Spec: svcapitypes.{{ $.CRD.Kind }}Spec{
{{- range $fieldName, $val := $test.FieldAssignments }}
			{{ $fieldName }}: {{ $val }},
{{- end }}
		},
	}

	// Create
{{- range $fieldName, $val := $test.FieldAssignments }}
	t.Logf("  {{ $fieldName }}: %s", acktest.FormatVal(resource.Spec.{{ $fieldName }}))
{{- end }}
	t.Logf("creating {{ $.CRD.Kind }} %s in namespace %s", name, acktest.Namespace())
	createStart := time.Now()
	err := acktest.CreateResource(ctx, resource)
	require.NoError(t, err, "failed to create {{ $.CRD.Kind }}")
	t.Logf("{{ $.CRD.Kind }} %s created successfully (took %s)", name, time.Since(createStart))
	t.Cleanup(func() {
		t.Logf("deleting {{ $.CRD.Kind }} %s", name)
		deleteStart := time.Now()
		if err := acktest.DeleteResource(context.Background(), resource); err != nil {
			t.Logf("warning: failed to delete {{ $.CRD.Kind }} %s: %v", name, err)
		} else {
			t.Logf("{{ $.CRD.Kind }} %s deleted (took %s)", name, time.Since(deleteStart))
		}
	})

	// Wait for sync
	t.Logf("waiting for {{ $.CRD.Kind }} %s to become synced (timeout: {{ $test.CreateWaitDuration }})", name)
	syncStart := time.Now()
	err = acktest.WaitForCondition(ctx, resource, "ACK.ResourceSynced", "True", {{ $test.CreateWaitDuration }})
	require.NoError(t, err, "{{ $.CRD.Kind }} did not become synced")
	t.Logf("{{ $.CRD.Kind }} %s synced (took %s)", name, time.Since(syncStart))
{{ if $test.HasVerification }}
	// Verify in AWS after create
	t.Logf("verifying {{ $.CRD.Kind }} %s in AWS...", name)
{{- range $test.CreateVerifyCalls }}
	{
		resp, err := awsClient.{{ .OperationName }}(ctx, &svcsdk.{{ .InputTypeName }}{
{{- range $member, $expr := .IdentifierAssignments }}
			{{ $member }}: {{ $expr }},
{{- end }}
		})
		require.NoError(t, err, "{{ .OperationName }} failed")
{{- range .Assertions }}
{{- if .DerefFunc }}
		require.Equal(t, {{ .Expected }}, {{ .DerefFunc }}(resp.{{ .ResponsePath }}), "{{ .Message }}")
{{- else }}
		require.Equal(t, {{ .Expected }}, resp.{{ .ResponsePath }}, "{{ .Message }}")
{{- end }}
{{- end }}
	}
{{- end }}
	t.Logf("AWS verification passed for {{ $.CRD.Kind }} %s", name)
{{ end }}
{{ if $test.HasUpdate }}
	// Update
	err = acktest.GetResource(ctx, resource)
	require.NoError(t, err, "failed to get {{ $.CRD.Kind }} before update")
	updated := resource.DeepCopy()
{{- range $fieldName, $val := $test.UpdateAssignments }}
	updated.Spec.{{ $fieldName }} = {{ $val }}
{{- end }}
	t.Logf("updating {{ $.CRD.Kind }} %s:", name)
{{- range $fieldName, $val := $test.UpdateAssignments }}
	t.Logf("  {{ $fieldName }}: %s", acktest.FormatVal(updated.Spec.{{ $fieldName }}))
{{- end }}
	updateStart := time.Now()
	err = acktest.UpdateResource(ctx, updated)
	require.NoError(t, err, "failed to update {{ $.CRD.Kind }}")
	t.Logf("{{ $.CRD.Kind }} %s update applied (took %s)", name, time.Since(updateStart))

	time.Sleep(5 * time.Second)

	t.Logf("waiting for {{ $.CRD.Kind }} %s to re-sync after update (timeout: {{ $test.CreateWaitDuration }})", name)
	resyncStart := time.Now()
	err = acktest.WaitForCondition(ctx, updated, "ACK.ResourceSynced", "True", {{ $test.CreateWaitDuration }})
	require.NoError(t, err, "{{ $.CRD.Kind }} did not re-sync after update")
	t.Logf("{{ $.CRD.Kind }} %s re-synced after update (took %s)", name, time.Since(resyncStart))
{{ if gt (len $test.UpdateVerifyCalls) 0 }}
	// Verify in AWS after update
	t.Logf("verifying {{ $.CRD.Kind }} %s in AWS after update...", name)
{{- range $test.UpdateVerifyCalls }}
	{
		resp, err := awsClient.{{ .OperationName }}(ctx, &svcsdk.{{ .InputTypeName }}{
{{- range $member, $expr := .IdentifierAssignments }}
			{{ $member }}: {{ $expr }},
{{- end }}
		})
		require.NoError(t, err, "{{ .OperationName }} failed after update")
{{- range .Assertions }}
{{- if .DerefFunc }}
		require.Equal(t, {{ .Expected }}, {{ .DerefFunc }}(resp.{{ .ResponsePath }}), "{{ .Message }}")
{{- else }}
		require.Equal(t, {{ .Expected }}, resp.{{ .ResponsePath }}, "{{ .Message }}")
{{- end }}
{{- end }}
	}
{{- end }}
	t.Logf("AWS verification after update passed for {{ $.CRD.Kind }} %s", name)
{{ end }}
{{ end -}}
}
{{ end }}
