# Code generated by ack-generate. DO NOT EDIT.
#
# Makefile for the ACK {{ .ServicePackageName }} controller.
# Run 'make help' to see available targets.

SHELL := /bin/bash

SERVICE := {{ .ServicePackageName }}

# Build configuration
VERSION ?= $(shell git describe --tags --always --dirty 2>/dev/null || echo "v0.0.0")
GITCOMMIT = $(shell git rev-parse HEAD)
BUILDDATE = $(shell date -u +'%Y-%m-%dT%H:%M:%SZ')
GO_LDFLAGS = -ldflags "-X main.version=$(VERSION) -X main.buildHash=$(GITCOMMIT) -X main.buildDate=$(BUILDDATE)"

# Controller runtime configuration
AWS_REGION ?= us-west-2

.PHONY: all build test local-test ensure-ack-generate generate release check-crd-compatibility run version help

all: test

build:              ## Build the controller binary
	@go build $(GO_LDFLAGS) -o bin/controller cmd/controller/main.go

test:               ## Run unit tests
	@go test ./...

local-test:         ## Run unit tests using go.local.mod
	@go test -modfile=go.local.mod ./...

ACK_GENERATE_VERSION ?= main

ensure-ack-generate:
	@go install github.com/aws-controllers-k8s/code-generator/cmd/ack-generate@$(ACK_GENERATE_VERSION)

generate: ensure-ack-generate release ## Regenerate controller code and release artifacts
	@ack-generate controller $(SERVICE)

RELEASE_VERSION ?= $(shell git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0-non-release-version")

release: ensure-ack-generate ## Generate release artifacts (override with RELEASE_VERSION=v1.2.4)
	@ack-generate release $(SERVICE) $(RELEASE_VERSION)

BASE_REF ?= main
CRD_PATHS ?= config/crd/bases,helm/crds

check-crd-compatibility: ensure-ack-generate ## Check CRDs for breaking changes against BASE_REF
	@ack-generate crd-compat-check --base-ref=$(BASE_REF) --crd-paths=$(CRD_PATHS)

run:                ## Run the controller locally (AWS_REGION=us-west-2)
	@go run ./cmd/controller/main.go \
		--aws-region=$(AWS_REGION) \
		--enable-development-logging \
		--log-level=debug

version:            ## Print the current version
	@echo $(VERSION)

help:               ## Show this help
	@echo "Usage: make [target]"
	@echo ""
	@echo "Targets:"
	@grep -E '^[a-zA-Z_-]+:.*##' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*##"}; {printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2}'

-include Makefile.custom
