//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlarmHistoryItem) DeepCopyInto(out *AlarmHistoryItem) {
	*out = *in
	if in.AlarmName != nil {
		in, out := &in.AlarmName, &out.AlarmName
		*out = new(string)
		**out = **in
	}
	if in.AlarmType != nil {
		in, out := &in.AlarmType, &out.AlarmType
		*out = new(string)
		**out = **in
	}
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlarmHistoryItem.
func (in *AlarmHistoryItem) DeepCopy() *AlarmHistoryItem {
	if in == nil {
		return nil
	}
	out := new(AlarmHistoryItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnomalyDetector) DeepCopyInto(out *AnomalyDetector) {
	*out = *in
	if in.Dimensions != nil {
		in, out := &in.Dimensions, &out.Dimensions
		*out = make([]*Dimension, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Dimension)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.MetricName != nil {
		in, out := &in.MetricName, &out.MetricName
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnomalyDetector.
func (in *AnomalyDetector) DeepCopy() *AnomalyDetector {
	if in == nil {
		return nil
	}
	out := new(AnomalyDetector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompositeAlarm) DeepCopyInto(out *CompositeAlarm) {
	*out = *in
	if in.ActionsEnabled != nil {
		in, out := &in.ActionsEnabled, &out.ActionsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ActionsSuppressedBy != nil {
		in, out := &in.ActionsSuppressedBy, &out.ActionsSuppressedBy
		*out = new(string)
		**out = **in
	}
	if in.ActionsSuppressedReason != nil {
		in, out := &in.ActionsSuppressedReason, &out.ActionsSuppressedReason
		*out = new(string)
		**out = **in
	}
	if in.ActionsSuppressor != nil {
		in, out := &in.ActionsSuppressor, &out.ActionsSuppressor
		*out = new(string)
		**out = **in
	}
	if in.ActionsSuppressorExtensionPeriod != nil {
		in, out := &in.ActionsSuppressorExtensionPeriod, &out.ActionsSuppressorExtensionPeriod
		*out = new(int64)
		**out = **in
	}
	if in.ActionsSuppressorWaitPeriod != nil {
		in, out := &in.ActionsSuppressorWaitPeriod, &out.ActionsSuppressorWaitPeriod
		*out = new(int64)
		**out = **in
	}
	if in.AlarmActions != nil {
		in, out := &in.AlarmActions, &out.AlarmActions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AlarmARN != nil {
		in, out := &in.AlarmARN, &out.AlarmARN
		*out = new(string)
		**out = **in
	}
	if in.AlarmConfigurationUpdatedTimestamp != nil {
		in, out := &in.AlarmConfigurationUpdatedTimestamp, &out.AlarmConfigurationUpdatedTimestamp
		*out = (*in).DeepCopy()
	}
	if in.AlarmDescription != nil {
		in, out := &in.AlarmDescription, &out.AlarmDescription
		*out = new(string)
		**out = **in
	}
	if in.AlarmName != nil {
		in, out := &in.AlarmName, &out.AlarmName
		*out = new(string)
		**out = **in
	}
	if in.AlarmRule != nil {
		in, out := &in.AlarmRule, &out.AlarmRule
		*out = new(string)
		**out = **in
	}
	if in.InsufficientDataActions != nil {
		in, out := &in.InsufficientDataActions, &out.InsufficientDataActions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.OKActions != nil {
		in, out := &in.OKActions, &out.OKActions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.StateReason != nil {
		in, out := &in.StateReason, &out.StateReason
		*out = new(string)
		**out = **in
	}
	if in.StateReasonData != nil {
		in, out := &in.StateReasonData, &out.StateReasonData
		*out = new(string)
		**out = **in
	}
	if in.StateTransitionedTimestamp != nil {
		in, out := &in.StateTransitionedTimestamp, &out.StateTransitionedTimestamp
		*out = (*in).DeepCopy()
	}
	if in.StateUpdatedTimestamp != nil {
		in, out := &in.StateUpdatedTimestamp, &out.StateUpdatedTimestamp
		*out = (*in).DeepCopy()
	}
	if in.StateValue != nil {
		in, out := &in.StateValue, &out.StateValue
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompositeAlarm.
func (in *CompositeAlarm) DeepCopy() *CompositeAlarm {
	if in == nil {
		return nil
	}
	out := new(CompositeAlarm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Datapoint) DeepCopyInto(out *Datapoint) {
	*out = *in
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = (*in).DeepCopy()
	}
	if in.Unit != nil {
		in, out := &in.Unit, &out.Unit
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Datapoint.
func (in *Datapoint) DeepCopy() *Datapoint {
	if in == nil {
		return nil
	}
	out := new(Datapoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dimension) DeepCopyInto(out *Dimension) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dimension.
func (in *Dimension) DeepCopy() *Dimension {
	if in == nil {
		return nil
	}
	out := new(Dimension)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DimensionFilter) DeepCopyInto(out *DimensionFilter) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DimensionFilter.
func (in *DimensionFilter) DeepCopy() *DimensionFilter {
	if in == nil {
		return nil
	}
	out := new(DimensionFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InsightRuleContributorDatapoint) DeepCopyInto(out *InsightRuleContributorDatapoint) {
	*out = *in
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InsightRuleContributorDatapoint.
func (in *InsightRuleContributorDatapoint) DeepCopy() *InsightRuleContributorDatapoint {
	if in == nil {
		return nil
	}
	out := new(InsightRuleContributorDatapoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InsightRuleMetricDatapoint) DeepCopyInto(out *InsightRuleMetricDatapoint) {
	*out = *in
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InsightRuleMetricDatapoint.
func (in *InsightRuleMetricDatapoint) DeepCopy() *InsightRuleMetricDatapoint {
	if in == nil {
		return nil
	}
	out := new(InsightRuleMetricDatapoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedRule) DeepCopyInto(out *ManagedRule) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedRule.
func (in *ManagedRule) DeepCopy() *ManagedRule {
	if in == nil {
		return nil
	}
	out := new(ManagedRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Metric) DeepCopyInto(out *Metric) {
	*out = *in
	if in.Dimensions != nil {
		in, out := &in.Dimensions, &out.Dimensions
		*out = make([]*Dimension, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Dimension)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.MetricName != nil {
		in, out := &in.MetricName, &out.MetricName
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Metric.
func (in *Metric) DeepCopy() *Metric {
	if in == nil {
		return nil
	}
	out := new(Metric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricAlarm) DeepCopyInto(out *MetricAlarm) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricAlarm.
func (in *MetricAlarm) DeepCopy() *MetricAlarm {
	if in == nil {
		return nil
	}
	out := new(MetricAlarm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MetricAlarm) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricAlarmList) DeepCopyInto(out *MetricAlarmList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MetricAlarm, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricAlarmList.
func (in *MetricAlarmList) DeepCopy() *MetricAlarmList {
	if in == nil {
		return nil
	}
	out := new(MetricAlarmList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MetricAlarmList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricAlarmSpec) DeepCopyInto(out *MetricAlarmSpec) {
	*out = *in
	if in.ActionsEnabled != nil {
		in, out := &in.ActionsEnabled, &out.ActionsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AlarmActions != nil {
		in, out := &in.AlarmActions, &out.AlarmActions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AlarmDescription != nil {
		in, out := &in.AlarmDescription, &out.AlarmDescription
		*out = new(string)
		**out = **in
	}
	if in.ComparisonOperator != nil {
		in, out := &in.ComparisonOperator, &out.ComparisonOperator
		*out = new(string)
		**out = **in
	}
	if in.DatapointsToAlarm != nil {
		in, out := &in.DatapointsToAlarm, &out.DatapointsToAlarm
		*out = new(int64)
		**out = **in
	}
	if in.Dimensions != nil {
		in, out := &in.Dimensions, &out.Dimensions
		*out = make([]*Dimension, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Dimension)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.EvaluateLowSampleCountPercentile != nil {
		in, out := &in.EvaluateLowSampleCountPercentile, &out.EvaluateLowSampleCountPercentile
		*out = new(string)
		**out = **in
	}
	if in.EvaluationPeriods != nil {
		in, out := &in.EvaluationPeriods, &out.EvaluationPeriods
		*out = new(int64)
		**out = **in
	}
	if in.ExtendedStatistic != nil {
		in, out := &in.ExtendedStatistic, &out.ExtendedStatistic
		*out = new(string)
		**out = **in
	}
	if in.InsufficientDataActions != nil {
		in, out := &in.InsufficientDataActions, &out.InsufficientDataActions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.MetricName != nil {
		in, out := &in.MetricName, &out.MetricName
		*out = new(string)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]*MetricDataQuery, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(MetricDataQuery)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.OKActions != nil {
		in, out := &in.OKActions, &out.OKActions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Period != nil {
		in, out := &in.Period, &out.Period
		*out = new(int64)
		**out = **in
	}
	if in.Statistic != nil {
		in, out := &in.Statistic, &out.Statistic
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Threshold != nil {
		in, out := &in.Threshold, &out.Threshold
		*out = new(float64)
		**out = **in
	}
	if in.ThresholdMetricID != nil {
		in, out := &in.ThresholdMetricID, &out.ThresholdMetricID
		*out = new(string)
		**out = **in
	}
	if in.TreatMissingData != nil {
		in, out := &in.TreatMissingData, &out.TreatMissingData
		*out = new(string)
		**out = **in
	}
	if in.Unit != nil {
		in, out := &in.Unit, &out.Unit
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricAlarmSpec.
func (in *MetricAlarmSpec) DeepCopy() *MetricAlarmSpec {
	if in == nil {
		return nil
	}
	out := new(MetricAlarmSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricAlarmStatus) DeepCopyInto(out *MetricAlarmStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricAlarmStatus.
func (in *MetricAlarmStatus) DeepCopy() *MetricAlarmStatus {
	if in == nil {
		return nil
	}
	out := new(MetricAlarmStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricAlarm_SDK) DeepCopyInto(out *MetricAlarm_SDK) {
	*out = *in
	if in.ActionsEnabled != nil {
		in, out := &in.ActionsEnabled, &out.ActionsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AlarmActions != nil {
		in, out := &in.AlarmActions, &out.AlarmActions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AlarmARN != nil {
		in, out := &in.AlarmARN, &out.AlarmARN
		*out = new(string)
		**out = **in
	}
	if in.AlarmConfigurationUpdatedTimestamp != nil {
		in, out := &in.AlarmConfigurationUpdatedTimestamp, &out.AlarmConfigurationUpdatedTimestamp
		*out = (*in).DeepCopy()
	}
	if in.AlarmDescription != nil {
		in, out := &in.AlarmDescription, &out.AlarmDescription
		*out = new(string)
		**out = **in
	}
	if in.AlarmName != nil {
		in, out := &in.AlarmName, &out.AlarmName
		*out = new(string)
		**out = **in
	}
	if in.ComparisonOperator != nil {
		in, out := &in.ComparisonOperator, &out.ComparisonOperator
		*out = new(string)
		**out = **in
	}
	if in.DatapointsToAlarm != nil {
		in, out := &in.DatapointsToAlarm, &out.DatapointsToAlarm
		*out = new(int64)
		**out = **in
	}
	if in.Dimensions != nil {
		in, out := &in.Dimensions, &out.Dimensions
		*out = make([]*Dimension, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Dimension)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.EvaluateLowSampleCountPercentile != nil {
		in, out := &in.EvaluateLowSampleCountPercentile, &out.EvaluateLowSampleCountPercentile
		*out = new(string)
		**out = **in
	}
	if in.EvaluationPeriods != nil {
		in, out := &in.EvaluationPeriods, &out.EvaluationPeriods
		*out = new(int64)
		**out = **in
	}
	if in.EvaluationState != nil {
		in, out := &in.EvaluationState, &out.EvaluationState
		*out = new(string)
		**out = **in
	}
	if in.ExtendedStatistic != nil {
		in, out := &in.ExtendedStatistic, &out.ExtendedStatistic
		*out = new(string)
		**out = **in
	}
	if in.InsufficientDataActions != nil {
		in, out := &in.InsufficientDataActions, &out.InsufficientDataActions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.MetricName != nil {
		in, out := &in.MetricName, &out.MetricName
		*out = new(string)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]*MetricDataQuery, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(MetricDataQuery)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.OKActions != nil {
		in, out := &in.OKActions, &out.OKActions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Period != nil {
		in, out := &in.Period, &out.Period
		*out = new(int64)
		**out = **in
	}
	if in.StateReason != nil {
		in, out := &in.StateReason, &out.StateReason
		*out = new(string)
		**out = **in
	}
	if in.StateReasonData != nil {
		in, out := &in.StateReasonData, &out.StateReasonData
		*out = new(string)
		**out = **in
	}
	if in.StateTransitionedTimestamp != nil {
		in, out := &in.StateTransitionedTimestamp, &out.StateTransitionedTimestamp
		*out = (*in).DeepCopy()
	}
	if in.StateUpdatedTimestamp != nil {
		in, out := &in.StateUpdatedTimestamp, &out.StateUpdatedTimestamp
		*out = (*in).DeepCopy()
	}
	if in.StateValue != nil {
		in, out := &in.StateValue, &out.StateValue
		*out = new(string)
		**out = **in
	}
	if in.Statistic != nil {
		in, out := &in.Statistic, &out.Statistic
		*out = new(string)
		**out = **in
	}
	if in.Threshold != nil {
		in, out := &in.Threshold, &out.Threshold
		*out = new(float64)
		**out = **in
	}
	if in.ThresholdMetricID != nil {
		in, out := &in.ThresholdMetricID, &out.ThresholdMetricID
		*out = new(string)
		**out = **in
	}
	if in.TreatMissingData != nil {
		in, out := &in.TreatMissingData, &out.TreatMissingData
		*out = new(string)
		**out = **in
	}
	if in.Unit != nil {
		in, out := &in.Unit, &out.Unit
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricAlarm_SDK.
func (in *MetricAlarm_SDK) DeepCopy() *MetricAlarm_SDK {
	if in == nil {
		return nil
	}
	out := new(MetricAlarm_SDK)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricDataQuery) DeepCopyInto(out *MetricDataQuery) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.Expression != nil {
		in, out := &in.Expression, &out.Expression
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
	if in.MetricStat != nil {
		in, out := &in.MetricStat, &out.MetricStat
		*out = new(MetricStat)
		(*in).DeepCopyInto(*out)
	}
	if in.Period != nil {
		in, out := &in.Period, &out.Period
		*out = new(int64)
		**out = **in
	}
	if in.ReturnData != nil {
		in, out := &in.ReturnData, &out.ReturnData
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricDataQuery.
func (in *MetricDataQuery) DeepCopy() *MetricDataQuery {
	if in == nil {
		return nil
	}
	out := new(MetricDataQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricDataResult) DeepCopyInto(out *MetricDataResult) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricDataResult.
func (in *MetricDataResult) DeepCopy() *MetricDataResult {
	if in == nil {
		return nil
	}
	out := new(MetricDataResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricDatum) DeepCopyInto(out *MetricDatum) {
	*out = *in
	if in.Dimensions != nil {
		in, out := &in.Dimensions, &out.Dimensions
		*out = make([]*Dimension, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Dimension)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.MetricName != nil {
		in, out := &in.MetricName, &out.MetricName
		*out = new(string)
		**out = **in
	}
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = (*in).DeepCopy()
	}
	if in.Unit != nil {
		in, out := &in.Unit, &out.Unit
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricDatum.
func (in *MetricDatum) DeepCopy() *MetricDatum {
	if in == nil {
		return nil
	}
	out := new(MetricDatum)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricMathAnomalyDetector) DeepCopyInto(out *MetricMathAnomalyDetector) {
	*out = *in
	if in.MetricDataQueries != nil {
		in, out := &in.MetricDataQueries, &out.MetricDataQueries
		*out = make([]*MetricDataQuery, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(MetricDataQuery)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricMathAnomalyDetector.
func (in *MetricMathAnomalyDetector) DeepCopy() *MetricMathAnomalyDetector {
	if in == nil {
		return nil
	}
	out := new(MetricMathAnomalyDetector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricStat) DeepCopyInto(out *MetricStat) {
	*out = *in
	if in.Metric != nil {
		in, out := &in.Metric, &out.Metric
		*out = new(Metric)
		(*in).DeepCopyInto(*out)
	}
	if in.Period != nil {
		in, out := &in.Period, &out.Period
		*out = new(int64)
		**out = **in
	}
	if in.Stat != nil {
		in, out := &in.Stat, &out.Stat
		*out = new(string)
		**out = **in
	}
	if in.Unit != nil {
		in, out := &in.Unit, &out.Unit
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricStat.
func (in *MetricStat) DeepCopy() *MetricStat {
	if in == nil {
		return nil
	}
	out := new(MetricStat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricStreamEntry) DeepCopyInto(out *MetricStreamEntry) {
	*out = *in
	if in.CreationDate != nil {
		in, out := &in.CreationDate, &out.CreationDate
		*out = (*in).DeepCopy()
	}
	if in.LastUpdateDate != nil {
		in, out := &in.LastUpdateDate, &out.LastUpdateDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricStreamEntry.
func (in *MetricStreamEntry) DeepCopy() *MetricStreamEntry {
	if in == nil {
		return nil
	}
	out := new(MetricStreamEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricStreamFilter) DeepCopyInto(out *MetricStreamFilter) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricStreamFilter.
func (in *MetricStreamFilter) DeepCopy() *MetricStreamFilter {
	if in == nil {
		return nil
	}
	out := new(MetricStreamFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricStreamStatisticsMetric) DeepCopyInto(out *MetricStreamStatisticsMetric) {
	*out = *in
	if in.MetricName != nil {
		in, out := &in.MetricName, &out.MetricName
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricStreamStatisticsMetric.
func (in *MetricStreamStatisticsMetric) DeepCopy() *MetricStreamStatisticsMetric {
	if in == nil {
		return nil
	}
	out := new(MetricStreamStatisticsMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Range) DeepCopyInto(out *Range) {
	*out = *in
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Range.
func (in *Range) DeepCopy() *Range {
	if in == nil {
		return nil
	}
	out := new(Range)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SingleMetricAnomalyDetector) DeepCopyInto(out *SingleMetricAnomalyDetector) {
	*out = *in
	if in.Dimensions != nil {
		in, out := &in.Dimensions, &out.Dimensions
		*out = make([]*Dimension, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Dimension)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.MetricName != nil {
		in, out := &in.MetricName, &out.MetricName
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SingleMetricAnomalyDetector.
func (in *SingleMetricAnomalyDetector) DeepCopy() *SingleMetricAnomalyDetector {
	if in == nil {
		return nil
	}
	out := new(SingleMetricAnomalyDetector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tag) DeepCopyInto(out *Tag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tag.
func (in *Tag) DeepCopy() *Tag {
	if in == nil {
		return nil
	}
	out := new(Tag)
	in.DeepCopyInto(out)
	return out
}
