name: version-check
on:
  pull_request:
    branches:
      - main
    paths:
      - Makefile
      - go.mod

jobs:
  version-check:
    name: runtime version in-sync
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - name: make check-versions
        run: make check-versions